# Generated by Django 3.1.7 on 2021-03-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncellenme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
    ]
